# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Lab5/Lab5.cache/wt [current_project]
set_property parent.project_path E:/Lab5/Lab5.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/Lab5/Lab5.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  E:/Lab5/Lab5.srcs/sources_1/imports/sources/accelerometer.sv
  E:/Lab5/Lab5.srcs/sources_1/new/keyboard.sv
  E:/Lab5/Lab5.srcs/sources_1/new/sound.sv
  E:/Lab5/Lab5.srcs/sources_1/new/io_demo.sv
}
read_vhdl -library xil_defaultlib {
  E:/Lab5/Lab5.srcs/sources_1/imports/sources/ADXL362Ctrl.vhd
  E:/Lab5/Lab5.srcs/sources_1/imports/sources/AccelArithmetics.vhd
  E:/Lab5/Lab5.srcs/sources_1/imports/sources/AccelerometerCtl.vhd
  E:/Lab5/Lab5.srcs/sources_1/imports/sources/SPI_If.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Lab5/Lab5.srcs/constrs_1/new/clock.xdc
set_property used_in_implementation false [get_files E:/Lab5/Lab5.srcs/constrs_1/new/clock.xdc]

read_xdc E:/Lab5/Lab5.srcs/constrs_1/imports/new/segdisplay.xdc
set_property used_in_implementation false [get_files E:/Lab5/Lab5.srcs/constrs_1/imports/new/segdisplay.xdc]

read_xdc E:/Lab5/Lab5.srcs/constrs_1/new/keyboard.xdc
set_property used_in_implementation false [get_files E:/Lab5/Lab5.srcs/constrs_1/new/keyboard.xdc]

read_xdc E:/Lab5/Lab5.srcs/constrs_1/new/sound.xdc
set_property used_in_implementation false [get_files E:/Lab5/Lab5.srcs/constrs_1/new/sound.xdc]

read_xdc E:/Lab5/Lab5.srcs/constrs_1/new/accel.xdc
set_property used_in_implementation false [get_files E:/Lab5/Lab5.srcs/constrs_1/new/accel.xdc]

read_xdc E:/Lab5/Lab5.srcs/constrs_1/new/led.xdc
set_property used_in_implementation false [get_files E:/Lab5/Lab5.srcs/constrs_1/new/led.xdc]


synth_design -top io_demo -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef io_demo.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file io_demo_utilization_synth.rpt -pb io_demo_utilization_synth.pb"
