# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/ProjectA2/ProjectA2.cache/wt [current_project]
set_property parent.project_path E:/ProjectA2/ProjectA2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/ProjectA2/ProjectA2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog E:/ProjectA2/ProjectA2.srcs/sources_1/imports/sources_1/imports/new/display640x480.vh
read_mem {
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/new/smem_screentest.mem
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/new/bmem_screentest.mem
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/new/dmem_screentest.mem
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/new/rfmem.mem
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/new/dmem_full-IO-test.mem
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/new/imem_full-IO-test.mem
  E:/ProjectA2/ProjectA2.srcs/sources_1/new/imem_screentest.mem
  E:/ProjectA2/ProjectA2.srcs/sources_1/new/imem_screentest_nopause.mem
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/541ASM/Checkers_imem.mem
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/541ASM/Checkers_bmem.mem
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/541ASM/Checkers_dmem.mem
  E:/ProjectA2/ProjectA2.srcs/sources_1/new/Checkers_smem.mem
}
read_verilog -library xil_defaultlib -sv {
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/sources_1/imports/sources_1/imports/sources_1/imports/sources_1/new/ALU.sv
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/sources_1/new/LED_reg.sv
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/sources_1/imports/sources_1/imports/lol/accelerometer.sv
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/sources_1/imports/sources_1/imports/sources_1/imports/sources_1/new/adder.sv
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/sources_1/imports/sources_1/imports/sources_1/imports/sources_1/new/addsub.sv
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/sources_1/imports/new/bitmapmem.sv
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/sources_1/new/clockdivider_Nexys4.sv
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/sources_1/imports/sources_1/imports/sources_1/imports/sources_1/new/comparator.sv
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/sources_1/imports/sources_1/new/controller.sv
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/sources_1/imports/sources_1/imports/sources_1/new/datapath.sv
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/sources_1/imports/imports/new/display8digit.sv
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/sources_1/imports/sources_1/new/dmem.sv
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/sources_1/imports/sources_1/imports/new/fulladder.sv
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/sources_1/imports/imports/new/hexto7seg.sv
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/sources_1/imports/sources_1/new/imem.sv
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/sources_1/imports/sources_1/new/keyboard.sv
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/sources_1/imports/sources_1/imports/sources_1/imports/sources_1/new/logical.sv
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/sources_1/new/memIO.sv
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/sources_1/imports/sources_1/new/mips.sv
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/sources_1/imports/sources_1/new/montek_sound_Nexys4.sv
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/sources_1/imports/sources_1/new/programcounter.sv
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/sources_1/imports/sources_1/imports/sources_1/new/register_file.sv
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/sources_1/imports/new/screenmem.sv
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/sources_1/imports/sources_1/imports/sources_1/imports/sources_1/new/shifter.sv
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/sources_1/new/sound_reg.sv
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/sources_1/imports/imports/sources_1/new/vgadisplaydriver.sv
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/sources_1/imports/imports/sources_1/new/vgatimer.sv
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/sources_1/imports/imports/sources_1/imports/new/xycounter.sv
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/sources_1/imports/sources_1/new/top.sv
}
read_vhdl -library xil_defaultlib {
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/sources_1/imports/sources_1/imports/lol/ADXL362Ctrl.vhd
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/sources_1/imports/sources_1/imports/lol/AccelArithmetics.vhd
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/sources_1/imports/sources_1/imports/lol/AccelerometerCtl.vhd
  E:/ProjectA2/ProjectA2.srcs/sources_1/imports/sources_1/imports/sources_1/imports/lol/SPI_If.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/ProjectA2/ProjectA2.srcs/constrs_1/imports/constrs_1/new/reset.xdc
set_property used_in_implementation false [get_files E:/ProjectA2/ProjectA2.srcs/constrs_1/imports/constrs_1/new/reset.xdc]

read_xdc E:/ProjectA2/ProjectA2.srcs/constrs_1/imports/constrs_1/new/vga.xdc
set_property used_in_implementation false [get_files E:/ProjectA2/ProjectA2.srcs/constrs_1/imports/constrs_1/new/vga.xdc]

read_xdc E:/ProjectA2/ProjectA2.srcs/constrs_1/imports/constrs_1/imports/constrs_1/new/accel.xdc
set_property used_in_implementation false [get_files E:/ProjectA2/ProjectA2.srcs/constrs_1/imports/constrs_1/imports/constrs_1/new/accel.xdc]

read_xdc E:/ProjectA2/ProjectA2.srcs/constrs_1/imports/constrs_1/imports/constrs_1/new/clock.xdc
set_property used_in_implementation false [get_files E:/ProjectA2/ProjectA2.srcs/constrs_1/imports/constrs_1/imports/constrs_1/new/clock.xdc]

read_xdc E:/ProjectA2/ProjectA2.srcs/constrs_1/imports/constrs_1/imports/constrs_1/new/keyboard.xdc
set_property used_in_implementation false [get_files E:/ProjectA2/ProjectA2.srcs/constrs_1/imports/constrs_1/imports/constrs_1/new/keyboard.xdc]

read_xdc E:/ProjectA2/ProjectA2.srcs/constrs_1/imports/constrs_1/imports/constrs_1/new/led.xdc
set_property used_in_implementation false [get_files E:/ProjectA2/ProjectA2.srcs/constrs_1/imports/constrs_1/imports/constrs_1/new/led.xdc]

read_xdc E:/ProjectA2/ProjectA2.srcs/constrs_1/imports/constrs_1/imports/constrs_1/new/sound.xdc
set_property used_in_implementation false [get_files E:/ProjectA2/ProjectA2.srcs/constrs_1/imports/constrs_1/imports/constrs_1/new/sound.xdc]

read_xdc E:/ProjectA2/ProjectA2.srcs/constrs_1/imports/constrs_1/imports/constrs_1/imports/new/segdisplay.xdc
set_property used_in_implementation false [get_files E:/ProjectA2/ProjectA2.srcs/constrs_1/imports/constrs_1/imports/constrs_1/imports/new/segdisplay.xdc]


synth_design -top top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
