# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Lab7/Lab7.cache/wt [current_project]
set_property parent.project_path E:/Lab7/Lab7.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/Lab7/Lab7.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog E:/Lab7/Lab7.srcs/sources_1/imports/new/display640x480.vh
read_mem {
  E:/Lab7/Lab7.srcs/sources_1/new/mem_data.mem
  E:/Lab7/Lab7.srcs/sources_1/new/bmem_screentest.mem
  E:/Lab7/Lab7.srcs/sources_1/new/smem_screentest.mem
}
read_verilog -library xil_defaultlib -sv {
  E:/Lab7/Lab7.srcs/sources_1/new/bitmap_mem.sv
  E:/Lab7/Lab7.srcs/sources_1/new/screen_mem.sv
  E:/Lab7/Lab7.srcs/sources_1/imports/new/vgadisplaydriver.sv
  E:/Lab7/Lab7.srcs/sources_1/imports/new/vgatimer.sv
  E:/Lab7/Lab7.srcs/sources_1/imports/new/xycounter.sv
  E:/Lab7/Lab7.srcs/sources_1/new/top.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Lab7/Lab7.srcs/constrs_1/new/clock.xdc
set_property used_in_implementation false [get_files E:/Lab7/Lab7.srcs/constrs_1/new/clock.xdc]

read_xdc E:/Lab7/Lab7.srcs/constrs_1/new/vga.xdc
set_property used_in_implementation false [get_files E:/Lab7/Lab7.srcs/constrs_1/new/vga.xdc]

read_xdc E:/Lab7/Lab7.srcs/constrs_1/new/reset.xdc
set_property used_in_implementation false [get_files E:/Lab7/Lab7.srcs/constrs_1/new/reset.xdc]


synth_design -top top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
